# Generated by Django 4.2 on 2023-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=512)),
                ('photo', models.URLField()),
                ('owner', models.IntegerField()),
                ('contacts', models.CharField(max_length=15)),
                ('category', models.IntegerField()),
                ('price', models.IntegerField()),
                ('publicationDate', models.DateTimeField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('permissions', models.IntegerField()),
                ('contacts', models.CharField(max_length=15)),
                ('fio', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
